import React, { useEffect, useState } from "react";
import MaterialTable, { Column } from "material-table";
import { Grid } from "@material-ui/core";
import DndList from "./DndList";
import { DndItem } from "./dnd-types";

const Table = () => {
  const [columns, setColumns] = useState(cols);
  const [dndItems, setDndItems] = useState<DndItem[]>(
    cols
      .filter((col) => !col.hidden)
      .map((col) => {
        const item: DndItem = {
          id: col.field as string,
          label: col.title as string,
        };
        return item;
      })
  );
  useEffect(() => {
    setColumns((cols) => {
      const newCols = cols
        .filter((col) => !col.hidden)
        .map((col) => ({
          ...col,
          order: dndItems.findIndex((item) => item.id === col.field),
        }))
        .sort((col1, col2) => col1.order - col2.order);

      console.log(
        "🚀 ~ file: Table.tsx ~ line 32 ~ setColumns ~ newCols",
        newCols
      );
      return newCols;
    });

    //TODO Refresh table, but expensive
  }, [dndItems]);

  return (
    <Grid container>
      <Grid item xs={2}>
        <DndList items={dndItems} setItems={setDndItems} />
      </Grid>
      <Grid item xs={10}>
        <MaterialTable columns={columns} data={data}></MaterialTable>
      </Grid>
    </Grid>
  );
};

const cols: Column<object>[] = [
  // Dates
  {
    field: "year",
    title: "Year",
    width: 120,
  },
  {
    field: "month",
    title: "Month",
    width: 120,
  },
  {
    field: "startDate",
    title: "Start Date",
    width: 120,
  },
  {
    field: "endDate",
    title: "End Date",
    width: 120,
  },
  {
    field: "tbc",
    title: "TBC",
    lookup: { true: "Yes", false: "No" },
    width: 120,
  },
  {
    field: "createdDate",
    title: "Created Date",
    width: 120,
  },
  {
    field: "fiscalYear",
    title: "Fiscal Year",
    width: 120,
  },

  // Promotion
  //   {
  //     field: "promotionId",
  //     title: "Event Id",
  //     width: 120,
  //   },
  //   {
  //     field: "eventName",
  //     title: "Event Name",
  //     width: 300,
  //   },
  //   {
  //     field: "promotionStatusName",
  //     title: "Status",
  //     width: 120,
  //   },
  //   {
  //     field: "createdBy",
  //     title: "Created By",
  //     width: 300,
  //   },

  //   // Customer
  //   {
  //     field: "customerType",
  //     title: "Customer Type",
  //     width: 120,
  //   },
  //   {
  //     field: "majorGroup",
  //     title: "Major Group",
  //     width: 120,
  //   },
  //   {
  //     field: "majorChain",
  //     title: "Major Chain",
  //     width: 120,
  //   },
  //   {
  //     field: "subChain",
  //     title: "Sub Chain",
  //     width: 120,
  //   },
  //   {
  //     field: "custRegion",
  //     title: "Customer Region",
  //     width: 120,
  //   },
  //   {
  //     field: "custName",
  //     title: "Customer Name",
  //     width: 300,
  //   },

  //   // Product
  //   {
  //     field: "businessUnit",
  //     title: "Business Unit",
  //     width: 120,
  //   },
  //   {
  //     field: "category",
  //     title: "Category",
  //     width: 120,
  //   },
  //   {
  //     field: "subCategory",
  //     title: "Sub Category",
  //     width: 120,
  //   },
  //   {
  //     field: "brand",
  //     title: "Brand",
  //     width: 120,
  //   },
  //   {
  //     field: "packSizeName",
  //     title: "Pack Size",
  //     width: 120,
  //   },
  //   {
  //     field: "productName",
  //     title: "Product Name",
  //     width: 300,
  //   },
  //   {
  //     field: "titan",
  //     title: "Titan",
  //     width: 120,
  //   },
  //   {
  //     field: "multiBuy",
  //     title: "MultiBuy",
  //     width: 120,
  //     type: "boolean",
  //   },
  //   {
  //     field: "comments",
  //     title: "Comments",
  //     width: 120,
  //   },

  //   // Amount Types
  //   {
  //     field: "marginSupport",
  //     title: "Margin Support",
  //     width: 120,
  //     type: "boolean",
  //   },
  //   {
  //     field: "marginSupportAmount",
  //     title: "Margin Amount",
  //     width: 120,
  //   },
  //   {
  //     field: "marginSupportPromotionSpendType",
  //     title: "Margin Spend Type",
  //     width: 120,
  //   },
  //   {
  //     field: "sally",
  //     title: "Sally",
  //     width: 120,
  //     type: "boolean",
  //   },
  //   {
  //     field: "sallyAmount",
  //     title: "Sally Amount",
  //     width: 120,
  //   },
  //   {
  //     field: "sallyPromotionSpendType",
  //     title: "Sally Spend Type",
  //     width: 120,
  //   },
  //   {
  //     field: "tally",
  //     title: "Tally",
  //     width: 120,
  //     type: "boolean",
  //   },
  //   {
  //     field: "tallyAmount",
  //     title: "Tally Amount",
  //     width: 120,
  //   },
  //   {
  //     field: "tallyPromotionSpendType",
  //     title: "Tally Spend Type",
  //     width: 120,
  //   },
  //   {
  //     field: "rsp",
  //     title: "N/a",
  //     width: 120,
  //     type: "boolean",
  //   },
  //   {
  //     field: "rspPromotionSpendType",
  //     title: "N/a Spend Type",
  //     width: 120,
  //   },
];

const data: object[] = [
  {
    promotionId: 119,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR JAN SPREADS WCAPE PROMO",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "11 Nov 2020",
    startDate: "25 Jan 2021",
    endDate: "07 Feb 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 122,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR ECAPE SPREADS PROMO",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "11 Nov 2020",
    startDate: "25 Jan 2021",
    endDate: "07 Feb 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 307,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "Spar Ecape Grocery Promo",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "17 Nov 2020",
    startDate: "11 Jan 2021",
    endDate: "24 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 317,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "Spar Inland Grocery Promo",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "17 Nov 2020",
    startDate: "11 Jan 2021",
    endDate: "24 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 74,
    createdBy: "Chanel.Naidoo@rclfoods.com",
    eventName: "MAKRO MORE FOR LESS M4L Q1 2021",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "10 Nov 2020",
    startDate: "01 Jan 2021",
    endDate: "31 Mar 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 79,
    createdBy: "Rosheal.Dhanookdhari@rclfoods.com",
    eventName: "MAKRO MORE FOR LESS",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2021,
    month: "Jan",
    tbc: false,
    createdDate: "10 Nov 2020",
    startDate: "01 Jan 2021",
    endDate: "31 Mar 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 192,
    createdBy: "Ashleigh.Stafford@rclfoods.com",
    eventName: "SPAR KZN CHICKEN PROMO FTF & DRUMS",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Planned",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "13 Nov 2020",
    startDate: "29 Dec 2020",
    endDate: "10 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 493,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Ouma Rusk 450gr Broadsheet ",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 494,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Ouma Rusk 500gr Broadsheet ",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
  {
    promotionId: 495,
    createdBy: "Lisa.Pillay@rclfoods.com",
    eventName: "Dec Month End Nola 500gr Core National Broadsheet",
    majorGroup: null,
    majorChain: null,
    subChain: null,
    promotionStatusId: 0,
    promotionStatusName: "Confirmed",
    customerType: null,
    custRegion: null,
    custName: null,
    category: null,
    subCategory: null,
    brand: null,
    packSizeName: null,
    productName: null,
    businessUnit: null,
    titan: null,
    multiBuy: false,
    comments: null,
    year: 2020,
    month: "Dec",
    tbc: false,
    createdDate: "19 Nov 2020",
    startDate: "28 Dec 2020",
    endDate: "03 Jan 2021",
    fiscalYear: "F21",
    marginSupport: false,
    marginSupportAmount: null,
    marginSupportPromotionSpendType: null,
    sally: false,
    sallyAmount: null,
    sallyPromotionSpendType: null,
    tally: false,
    tallyAmount: null,
    tallyPromotionSpendType: null,
    rsp: false,
    rspPromotionSpendType: null,
  },
];

export default Table;
